name: Labeler
on:
  pull_request_target:
    types:
      - opened
      - edited
      - ready_for_review
      - synchronize
  issue_comment:
    types: [created, edited]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install yq

      - name: Get Reviewers
        id: reviewers
        run: echo ::set-output name=reviewers::$(cat ./OWNERS | yq .reviewers -M | grep , | sed 's/[",]//g')

      - name: Get Approvers
        id: approvers
        run: echo ::set-output name=approvers::$(cat ./OWNERS | yq .approvers -M | grep , | sed 's/[",]//g')

      - name: Add Size label
        if: github.event_name == 'pull_request_target'
        uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_PAT }}"

      - name: Add WIP label / comment trigger
        if: |
          contains(github.event.pull_request.title, 'wip') ||
          (contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/wip'))
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          add-labels: 'WIP'

      - name: Remove WIP label
        if: |
          contains(github.event.comment.html_url, '/pull/') && 
          contains(github.event.comment.body, '/wip cancel')
        uses: andymckay/labeler@master
        with:
          repo-token: ${{ secrets.BOT_PAT }}
          remove-labels: 'WIP'
