name: Storybook
on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        env:
          CONTEXT: ${{ toJSON(github) }}
        run: echo "$CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        env:
          BRANCH: "${{ github.event_name == 'pull_request_target' && env.head_ref || 'main' }}"
        with:
          token: ${{ secrets.BOT_PAT }}
          branch: ${{ env.BRANCH }} # The branch the action should deploy to.
          folder: docs-build # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # The folder that we serve our Storybook files from
